apiVersion: apps/v1
kind: Deployment
metadata:
  name: performance-of-go-ipfs
  labels:
    app: performance-of-go-ipfs
spec:
  template:
    metadata:
      name: performance-of-go-ipfs
      labels:
        app: performance-of-go-ipfs
    spec:
      volumes:
      - hostPath:
          path: /data
        name: test-server-data
