apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-server-data-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 25Gi
  storageClassName: do-block-storage


