apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tmp-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  storageClassName: do-block-storage

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ipfs-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: do-block-storage
